add deployment script to pipeline
npm install before deploy script

get service creds into a file

debug key file

add testing section to pipeline

add confirmation log message in deploy tc script

added alive signal

test alive signal

use alive signal for cb

better comments

diff --git a/.bluemix/pipeline.yml b/.bluemix/pipeline.yml
--- a/.bluemix/pipeline.yml
+++ b/.bluemix/pipeline.yml
@@ -11,6 +11,9 @@ stages:
   - name: SERVICE_INSTANCE_NAME
     value: '{{sin}}'
     type: text
+  - name: ALIVE_SIGNAL
+    value: '{{alive_signal}}'
+    type: text
   - name: SAMPLE_REPO
     value: '{{SAMPLE_REPO}}'
     type: text
@@ -26,15 +29,20 @@ stages:
       #!/bin/bash
       export IBP_NAME="ibm-blockchain-5-dev"
       export IBP_PLAN="ibm-blockchain-plan-v1-ga1-dev"
+      export VCAP_KEY_NAME="marbles_tc_creds"
 
-      # Test Code
+      # -----------------------------------------------------------
+      # Test Code - ignore me
+      # -----------------------------------------------------------
       printf "\n --- Listing services for testing ---\n"
       cf services
       #cf services | sed -n 's/.*\(ibm-blockchain-plan-v1-prod\).*/\1/p'
       #cf services | sed -n 's/.*\(${SERVICE_INSTANCE_NAME}\).*/\1/p'
 
-      # Detect if there is already a service we should use
-      printf "\n --- Detecting service option---\n"
+      # -----------------------------------------------------------
+      # Detect if there is already a service we should use - [ Optional ]
+      # -----------------------------------------------------------
+      printf "\n --- Detecting service options ---\n"
       if [ "$SERVICE_INSTANCE_NAME" != "" ]; then
         echo "A service instance name was provided, lets use that"
       else
@@ -43,21 +51,97 @@ stages:
       fi
       printf "Using service instance name '${SERVICE_INSTANCE_NAME}'\n"
 
-      # Create a service, this is okay to run if the service already exists as long as its the same typeof service
+      # -----------------------------------------------------------
+      # Detect if we we have a callback url to hit when demo is alive - [ Optional ]
+      # -----------------------------------------------------------
+      if [ "$ALIVE_SIGNAL" != "" ]; then
+        echo "The alive signal url was provided, ${ALIVE_SIGNAL}"
+        #export ALIVE_SIGNAL=`echo $ALIVE_SIGNAL | sed -r 's/%3A/:/g'
+        curl -s --head $ALIVE_SIGNAL | head -n 1 | grep "HTTP/1.[01] [23].."
+      fi
+
+      # -----------------------------------------------------------
+      # 1. Test if everything we need is set
+      # -----------------------------------------------------------
+      printf "\n --- Testing if the script has what it needs ---\n"
+      export SCRIPT_ERROR="nope"
+       if [ "$IBP_NAME" == "" ]; then
+        echo "Error - bad script setup - IBP_NAME was not provided (IBM Blockchain service name)"
+        export SCRIPT_ERROR="yep"
+      fi
+      if [ "$IBP_PLAN" == "" ]; then
+        echo "Error - bad script setup - IBP_PLAN was not provided (IBM Blockchain service's plan name)"
+        export SCRIPT_ERROR="yep"
+      fi
+      if [ "$VCAP_KEY_NAME" == "" ]; then
+        echo "Error - bad script setup - VCAP_KEY_NAME was not provided (Bluemix service credential key name)"
+        export SCRIPT_ERROR="yep"
+      fi
+      if [ "$SERVICE_INSTANCE_NAME" == "" ]; then
+        echo "Error - bad script setup - SERVICE_INSTANCE_NAME was not provided (IBM Blockchain service instance name)"
+        export SCRIPT_ERROR="yep"
+      fi
+      if [ "$CF_APP" == "" ]; then
+        echo "Error - bad script setup - CF_APP was not provided (Marbles application name)"
+        export SCRIPT_ERROR="yep"
+      fi
+      if [ "$SCRIPT_ERROR" == "yep" ]; then
+        exit 1
+      else
+        echo "All good"
+      fi
+
+      # -----------------------------------------------------------
+      # 2. Create a service instance (this is okay to run if the service name already exists as long as its the same typeof service)
+      # -----------------------------------------------------------
       printf "\n --- Creating an instance of the IBM Blockchain Platform service ---\n"
       cf create-service ${IBP_NAME} ${IBP_PLAN} ${SERVICE_INSTANCE_NAME}
+      cf create-service-key ${SERVICE_INSTANCE_NAME} ${VCAP_KEY_NAME} -c '{"msp_id":"PeerOrg1"}'
 
-      # Push app (don't start yet, wait for binding)
+      # -----------------------------------------------------------
+      # 3. Get service credentials into our file system (remove the first two lines from cf service-key output)
+      # -----------------------------------------------------------
+      printf "\n --- Getting service credentials ---\n"
+      cf service-key ${SERVICE_INSTANCE_NAME} ${VCAP_KEY_NAME} > ./config/temp.txt
+      tail -n +2 ./config/temp.txt > ./config/marbles_tc.json
+      printf "\n --- testing temp.txt --- \n"
+      cat ./config/temp.txt -b
+      printf "\n --- testing marbles_tc.json --- \n"
+      cat ./config/marbles_tc.json -b
+
+      # -----------------------------------------------------------
+      # 4. Push application (don't start yet, wait for binding)
+      # -----------------------------------------------------------
       printf "\n --- Creating the Marbles application ---\n"
       cf push $CF_APP --no-start
 
-      # Bind app to the blockchain service
+      # -----------------------------------------------------------
+      # 5. Bind application to the blockchain service
+      # -----------------------------------------------------------
       printf "\n --- Binding the IBM Blockchain Platform service to Marbles ---\n"
       cf bind-service $CF_APP ${SERVICE_INSTANCE_NAME} -c "{\"permissions\":\"read-only\"}"
 
-      # Start her up
+      # -----------------------------------------------------------
+      # 6. Start her up
+      # -----------------------------------------------------------
       printf "\n --- Starting Marbles ---\n"
       cf start $CF_APP
-      #cf restage $CF_APP - this is not needed if we bind before starting
+
+      # -----------------------------------------------------------
+      # 7. Install and instantiate the chaincode (dsh disabled for now - todo bring it back)
+      # -----------------------------------------------------------
+      #printf "\n --- Setting up for deployment ---\n"
+      #export PATH=/opt/IBM/node-v6.7.0/bin:$PATH
+      #npm install
+      #printf "\n --- Deploying Chaincode ---\n"
+      #node ./scripts/deploy_chaincode.js || true
+
+      # -----------------------------------------------------------
+      # 8. Ping IBP that the application is alive  - [ Optional ]
+      # -----------------------------------------------------------
+      if [ "$ALIVE_SIGNAL" != "" ]; then
+        printf "\n --- Sending signal that the demo is alive ---\n"
+        curl -s --head $ALIVE_SIGNAL | head -n 1 | grep "HTTP/1.[01] [23].."
+      fi
 
       printf "\n\n --- We are done here. ---\n\n"
